version: "3"
services:

  lisk-explorer:
    image: lisk/explorer:3.0.0
    depends_on:
      - lisk-service
    ports:
      - "127.0.0.1:6040:6040"
    networks:
      - lisk-explorer
      - localhost
    restart: on-failure
    environment:
      - LISK_SERVICE_HOST=lisk-service

  lisk-service:
    image: lisk/service:0.1.0
    depends_on:
      - service-cache
      - freegeoip
    ports:
      - "127.0.0.1:6041:6041"
    networks:
      - lisk-explorer
      - localhost
    restart: on-failure
    environment:
      - LISK_HOST=ams1-testnet-explorer-001.lisk.io
      - LISK_PORT=7000
      - REDIS_HOST=service-cache
      - FREEGEOIP_HOST=freegeoip

  service-cache:
    image: redis:alpine
    networks:
      - lisk-explorer
    restart: on-failure

  service-cache-candles:
    image: lisk/service:0.1.0
    depends_on:
      - service-cache
    networks:
      - lisk-explorer
    environment:
      - REDIS_HOST=service-cache
    command: ./node_modules/grunt-cli/bin/grunt candles:build

  freegeoip:
    image: fiorix/freegeoip
    networks:
      - lisk-explorer
    restart: on-failure


networks:
  lisk-explorer:
  localhost:
    external: true
